name: Django Things Demo
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10-slim
    steps:
      - name: Clone from github
        uses: actions/checkout@v3
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python install -r requirements.txt
      - name: Run the server
        run: python manage.py runserver
          